### ISSUE TITLE
When running the IDE command in 1.17, a missing annotation error is thrown.

### ISSUE THREAD

**Issue by paperfour** [SpongePowered/MixinGradle#31] opened 2021-07-24 23:17 UTC
It might be my fault, but here's the message:

ForgeGradle: 5.1+
Forge: 1.17.1-37.0.7
MixinGradle: 0.7-SNAPSHOT

> What went wrong:
> A problem was found with the configuration of task ':eclipseFactoryPath' (type 'MixinEclipse.EclipseFactoryPath').
> 
>  In plugin 'org.spongepowered.mixin' type 'org.spongepowered.asm.gradle.plugins.MixinEclipse.EclipseFactoryPath' property 'config' has @Input annotation used on property of type 'Configuration'.
>  
> Reason: A property of type 'Configuration' annotated with @Input cannot determine how to interpret the file.

**Comment by NotUnfound** [comment] 2021-09-25 16:51
I don't believe so

**Comment by HaydenBelanger** [comment] 2021-10-30 18:47
Has this issue been resolved yet? Still receiving this error when trying to set up Mixins in FG5.

**Comment by DarkShadow44** [comment] 2021-10-30 22:59
I'm using https://github.com/SpongePowered/MixinGradle/pull/34 with eclipse buildship integration, which works fine for me. Maybe an alternative for you as well?

**Comment by HaydenBelanger** [comment] 2021-10-31 21:11
@DarkShadow44 thanks for the tip, I was able to get Eclipse working this way, but now I'm running into the issue where MixinGradle can't find `createMcpToSrg/output.tsrg`, and of course that means it can't generate the refmap. How did you end up getting around that?

**Comment by DarkShadow44** [comment] 2021-10-31 21:56
@HaydenBelanger 
You need to run createMcpToSrg. Or [put this](https://github.com/DarkShadow44/projectbabelfish/blob/1638c5763beee694276a2d9fb241b21c70fbc4d4/build.gradle#L112-L116) into your gradle.

**Comment by qMartinz** [comment] 2022-02-14 00:35
I'm having the same issue in 1.18.1, And this issue has been opn for almost a year now, did anyone figure it out?

**Comment by DarkShadow44** [comment] 2022-02-14 01:37
You're in luck, just today I decided to take matters into my own hands. If you can build from source, can you try https://github.com/DarkShadow44/MixinGradle/tree/task_fix ?

**Comment by FoxMcloud5655** [comment] 2022-07-03 19:32
This may be late, but your custom version works for me, @DarkShadow44.  Thank you!

**Comment by Cheos137** [comment] 2022-07-24 10:53
Just noticed this issue exists...
I think I've found the cause of this - see #40

The simplest solution is to just specify the 'mixingradle' plugin before/above the 'eclipse' plugin.
I hope that might help you all, too!

**Comment by FoxMcloud5655** [comment] 2023-01-24 23:44
For anyone encountering this in the future, @Cheos137's solution works perfectly fine in almost all situations I've run into.

**Comment by MegaPiggy** [comment] 2023-05-08 04:08
This is still happening and I am not able to fix it.

**Comment by Cheos137** [comment] 2023-06-07 13:26
seems to be working since commit 8381249 regardless of plugin specification order

**Comment by SizableShrimp** [comment] 2023-06-14 20:57
Should be fixed by https://github.com/SpongePowered/MixinGradle/commit/8381249e1cde376b9718a9855f0a09062742fc6b as noted from Cheos137. If not, comment here, and I can try to look into it (although I am not an Eclipse user).

**Closed by SizableShrimp** 2023-06-14 20:57 UTC
